---
title: "Uma Breve Inrodução ao R"
author: "Vitor José Landi Silvério"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Princípios Básicos

## Primeiros Passos

### Comandos Básicos

### Atribuição de Valores

### Tipos de Variáveis

### Utilizando Ajuda (help)

## Operações Básicas

## Estruturas Básicas

### Vetor

### Matriz

### Array

### Lista

### Data Frame

## Tabelas

### Tabelas Simples

### Tabelas de Contingência

### Tabelas de Proporção

## Funções

## Funções - Apply

### Apply

### Tapply

### Sapply

### Lapply

## Pacotes

## Entrada de Dados

### Csv

### Txt

### Xls ou Xlsx

### Base de dados do R

### Opções Importantes

### Conferência dos dados

### Funções Adicionais

# Estatística Básica

## Medidas de Posição

### Média

### Mediana

### Mínimo

### Máximo

### Quantis

### Moda

### Função Summary

## Medidas de Dispersão

### Variância

### Desvio Padrão

### Coeficiente de Variação

### Amplitude

## Correlação

### Coeficiente de Pearson

### Coeficiente de Kendall

### Coeficiente de Spearman


# Gráficos 

## Gráficos para Variáveis Qualitativas

### Gráfico de Barras

### Gráfico de Setores

## Gráficos para Variáveis Quantitativas

### Histograma

### Polígono de frequência

### Gráfico de Bastões

### Gráfico de Dispersão

### Gráfico de Caixas (*Boxplot*)

## Ajustes Gráficos

### Principais Ajustes

### Funções de sobreposição

### Argumento *type*

### Tipos de Símbolos e Linhas

### Texto e Legenda

### Utilizando *par* e comandos adicionais

### Cores

### Janelas gráficas externas

### Representando Tabelas de Contingência

### Representando Funções

### Exportano Gráficos



# Noções de Probabilidade

## Amostragem

## Análise Combinatória

### Permutação

### Arranjo

### Combinação

## Distribuições de Probabilidade

### Geração de valores aleatórios

## Função de Densidade / Probabilidade

## Função Acumulada

## Quantis